### ISSUE TITLE
Textnow has just updated API. The tool needs to Update

### ISSUE THREAD

**Issue by buidoi8x** [sillibird/Textnow-API-3#6]
Hello admin
Textnow has just updated API. The tool needs update.
Please fix it.
Thanks

**Comment by tecan** [comment]
they allow forwarding texts to email so most people would just do that till then.

**Comment by abdu1aziz** [comment]
I believe the older API_Key has been revoked. We need new API_KEY. Other than That I don't believe they changed a bunch.. I'd love to see the text-now back up and running... thanks in advance...

**Comment by buidoi8x** [comment]
The old API_Key is still working well. This tool has used Old API (tool send sms) and still working well: https://mmo4me.com/threads/tool-nuoi-clone-textnow-phien-ban-mau-me.382915/

The tool  need to change something to work again.
