### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by ghost** [sillibird/Textnow-API-3#7]
Traceback (most recent call last):
  File "messageTest.py", line 1, in <module>
    import textnow
  File "/etc/asterisk/page_api/textnow.py", line 22
    return hashlib.md5(f"{self.SIGN_KEY}{method}{node}{query}".encode()).hexdigest()
                                                             ^
SyntaxError: invalid syntax

**Comment by Allan-Cao** [comment]
Are you using python2?

**Comment by sillibird** [comment]
This library is for Python3, not 2.
