### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by azayek5** [sillibird/Textnow-API-3#9]
I have fixed the remote connection issue, but now I am having a problem with the sendReq method. The req results in a 'Integrity header validation failed", error_code="PARAMETER_MISSING". Any ideas on how to fix this? 

As a side note, are the textnow accounts platform exclusive? For instance, could I use a textnow account created on an iPhone to log in with this API as well as Android?

**Comment by azayek5** [comment]
I figured out the problem, all is well.

**Comment by xrpixer** [comment]
@azayek5 could you elaborate on how you fixed the "Remote end closed connection without response"? 
I'm having the same problem.
